// Env files a `next build` would read that name a different environment than
// the one being deployed. See docs/decisions/2026-10-01-deploy-pins-site-url.md.
//
// `next build` is always a production build, so Next loads .env.production.local
// (and .env.production, .env) for EVERY deploy, test included, and inlines their
// NEXT_PUBLIC_* values. The file is gitignored, so nothing else can see it.
// scripts/pi/write-env.mjs writes exactly such a file, for one environment.
import { existsSync, readFileSync } from "node:fs";

/** What a production `next build` reads that could belong to another environment. */
export const BUILD_LOADED_FILES = [".env.production.local", ".env.production", ".env"];

const originOf = (url) => {
  try {
    return new URL(url).origin;
  } catch {
    return null;
  }
};

/**
 * The files that name an environment other than `target`, each with why.
 * `siteOrigin` and `appEnvForSupabaseUrl` are the deploy's own answers for
 * `target`, so this and the deploy can't disagree about what "right" is.
 */
export function strayEnvFiles(target, { siteOrigin, expectedAppEnv, appEnvForSupabaseUrl, files = BUILD_LOADED_FILES, read }) {
  const readFile = read ?? ((f) => (existsSync(f) ? readFileSync(f, "utf8") : null));
  const stray = [];
  for (const file of files) {
    const text = readFile(file);
    if (text == null) continue;
    const vars = {};
    for (const line of text.split(/\r?\n/)) {
      const i = line.indexOf("=");
      if (i > 0 && !line.trim().startsWith("#")) vars[line.slice(0, i).trim()] = line.slice(i + 1).trim().replace(/^"|"$/g, "");
    }
    const why = [];
    const header = /generated by scripts\/pi\/write-env\.mjs for the (\w+) environment/i.exec(text)?.[1];
    if (header && header !== target) why.push(`written for the ${header} environment`);
    const site = vars.NEXT_PUBLIC_SITE_URL;
    if (site && originOf(site) !== originOf(siteOrigin)) why.push(`NEXT_PUBLIC_SITE_URL=${site}, not ${siteOrigin}`);
    const sb = vars.NEXT_PUBLIC_SUPABASE_URL;
    if (sb && appEnvForSupabaseUrl(sb) !== expectedAppEnv) why.push(`NEXT_PUBLIC_SUPABASE_URL is the ${appEnvForSupabaseUrl(sb)} project`);
    if (why.length) stray.push({ file, why: why.join("; ") });
  }
  return stray;
}
