// Write .env.production.local for `next build` / `next start` on the Pi.
//
// The Worker gets its values from the shell at build time and from wrangler
// secrets at run time (scripts/deploy.mjs). Plain Next.js instead reads
// .env.production.local, so this merges the same two files the rest of the
// tooling uses — .env.local with .env.deploy.production over it — into that
// one file. Gitignored (.env.*.local); regenerated by deploy-pi.sh on every
// deploy so a changed secret takes effect on the next restart.
//
//   node scripts/pi/write-env.mjs [--env production|uat|test]

import { writeFileSync } from "node:fs";
import { loadEnv, parseEnvArg, projectRef } from "../lib/env.mjs";

const { name } = parseEnvArg(process.argv.slice(2));
const env = loadEnv(name);

const KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "GOOGLE_OAUTH_CLIENT_ID",
  "GOOGLE_OAUTH_CLIENT_SECRET",
  "GOOGLE_OAUTH_REFRESH_TOKEN",
  "GOOGLE_DRIVE_ROOT_FOLDER_ID",
];
const missing = KEYS.filter((k) => !env[k]);
if (missing.length) {
  console.error(`write-env: missing for ${name}: ${missing.join(", ")}`);
  process.exit(2);
}

const lines = [
  `# Generated by scripts/pi/write-env.mjs for the ${name} environment — do not edit, do not commit.`,
  ...KEYS.map((k) => `${k}=${env[k]}`),
];
writeFileSync(".env.production.local", lines.join("\n") + "\n", { mode: 0o600 });
console.log(`write-env: .env.production.local → ${name} (Supabase ${projectRef(env)})`);
