// Write .env.production.local for `next build` / `next start` on the Pi.
//
// The Worker gets its values from the shell at build time and from wrangler
// secrets at run time (scripts/deploy.mjs). Plain Next.js instead reads
// .env.production.local, so this merges the same two files the rest of the
// tooling uses — .env.local with .env.deploy.production over it — into that
// one file. Gitignored (.env.*.local); regenerated by deploy-pi.sh on every
// deploy so a changed secret takes effect on the next restart.
//
//   node scripts/pi/write-env.mjs [--env production|uat|test]

import { writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { loadEnv, parseEnvArg, projectRef } from "../lib/env.mjs";
import { readWranglerConfig } from "../lib/wrangler.mjs";
import { ACTIONS_KEY_VAR, actionsKeyProblem } from "../lib/actions-key.mjs";
import { PI_OPTIONAL_SECRETS } from "../lib/optional-secrets.mjs";

// Pi only. On a dev machine this file is read by every `next build`, deploy:test
// included, and bakes this environment's host into the bundle without a trace
// (docs/decisions/2026-10-01-deploy-pins-site-url.md). The Pi is Linux, the dev
// machine is not; there is deliberately no flag past it.
if (process.platform !== "linux") {
  console.error(`write-env: this writes .env.production.local for the Pi and refuses to run on ${process.platform}.`);
  process.exit(2);
}

const { name } = parseEnvArg(process.argv.slice(2));
const env = loadEnv(name);

const KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "GOOGLE_OAUTH_CLIENT_ID",
  "GOOGLE_OAUTH_CLIENT_SECRET",
  "GOOGLE_OAUTH_REFRESH_TOKEN",
  "GOOGLE_DRIVE_ROOT_FOLDER_ID",
];
const missing = KEYS.filter((k) => !env[k]);
if (missing.length) {
  console.error(`write-env: missing for ${name}: ${missing.join(", ")}`);
  process.exit(2);
}

// The key the Worker's build also uses (scripts/deploy.mjs), so a form either
// renders is accepted by the other. Written to the file `next build` AND
// `next start` read, which is also what lets the running server decrypt with
// the key it was built with.
{
  const problem = actionsKeyProblem(env[ACTIONS_KEY_VAR]);
  if (problem) {
    console.error(`write-env: ${name}: ${problem}`);
    process.exit(2);
  }
}

// Worker vars the app reads at run time come from wrangler.jsonc, not the
// env files, so the Pi renders what the Worker would. PUBLIC_SITE is the
// one that matters: a Pi without it would serve the public website on a
// host the Worker keeps locked behind sign-in (src/lib/public-site.ts).
// readWranglerConfig() throws on a file it can't parse, which stops here
// rather than writing a file that silently leaves the site open.
const RUNTIME_VARS = ["PUBLIC_SITE"];
const wrangler = readWranglerConfig().env?.[name] ?? {};
const vars = wrangler.vars ?? {};

// The origin the visitor is actually on, pinned rather than derived.
// src/lib/site-origin.ts normally reads `x-forwarded-host`, and the Worker
// sets it to the public host — but cloudflared then receives the request at
// pi.lannacare.org and overwrites that header with its own ingress hostname,
// so on the Pi the app would believe it is pi.lannacare.org. That is the
// case site-origin.ts's own comment anticipates with NEXT_PUBLIC_SITE_URL.
// Without it, signInWithGoogle builds a redirectTo Supabase rejects as
// off-allow-list, and /auth/callback sends the browser somewhere it cannot
// reach. Taken from the Worker's own routes so there is one list of public
// hostnames, not two: the first is the canonical one (the apex, with www
// second), and it matches what cloudflared rewrites Host to.
const publicHost = (wrangler.routes ?? [])[0]?.pattern;
if (!publicHost) {
  console.error(
    `write-env: ${name} has no routes in wrangler.jsonc, so the public host is unknown. ` +
      `A Pi deploy needs one: add the route, or deploy an environment that has one.`,
  );
  process.exit(2);
}

const lines = [
  `# Generated by scripts/pi/write-env.mjs for the ${name} environment — do not edit, do not commit.`,
  ...KEYS.map((k) => `${k}=${env[k]}`),
  `${ACTIONS_KEY_VAR}=${env[ACTIONS_KEY_VAR]}`,
  // Optional, the same list the Worker gets (scripts/lib/optional-secrets.mjs):
  // the backup tile's folder and the visitor count's Cloudflare pair.
  ...PI_OPTIONAL_SECRETS.filter((k) => env[k]).map((k) => `${k}=${env[k]}`),
  ...RUNTIME_VARS.filter((k) => vars[k]).map((k) => `${k}=${vars[k]}`),
  `NEXT_PUBLIC_SITE_URL=https://${publicHost}`,
  // The sized-photo disk cache (src/lib/photo-cache.ts). Only a Pi has this
  // line, so the Worker fallback and `next dev` stay diskless. Disposable and
  // capped (PHOTO_CACHE_MAX_MB, default 1024), kept outside ~/backups.
  // Test has its own directory: it shares the Pi with production and its own cap.
  `PHOTO_CACHE_DIR=${join(homedir(), name === "test" ? "photo-cache-test" : "photo-cache")}`,
];
writeFileSync(".env.production.local", lines.join("\n") + "\n", { mode: 0o600 });
console.log(`write-env: .env.production.local → ${name} (Supabase ${projectRef(env)}, site https://${publicHost})`);
