#!/usr/bin/env node
// The merge train's gates in one command, with every exit code printed.
//
// Runs `npm run typecheck`, `npm run lint` and `npm run build` — the same
// three, in the same order, as the `check` job in .github/workflows/ci.yml —
// and ends with one line such as
//
//   gates: typecheck=0 lint=0 build=1
//
// Every gate runs even when an earlier one fails, and the exit status is
// non-zero if any of them did. That is the whole point: by hand, each of these
// has read as green without having run.
//
//   - `npm run build | tail` reports the exit status of `tail`.
//   - `A && B; echo $?` reports A's status when A fails, and B never runs.
//   - In a worktree where `npm ci` has not finished linking node_modules/.bin,
//     every script fails with "'next' is not recognized", which scrolls past as
//     noise. This script refuses to start in that state rather than report it
//     as three failures someone might skim.
//
// Paste the output into section 2 of the test plan as it is; it is the
// evidence, and it can be regenerated by running this again.
//
//   node scripts/gates.mjs          # typecheck, lint, build
//   node scripts/gates.mjs --plan   # ...then scripts/check-test-plan.mjs too
//
// `--plan` is opt-in because CI runs the test-plan check as a separate job that
// reports without blocking, and a correct plan stays red until a person signs
// it — folding that into the default would make the gates red for most of a
// PR's life and teach everyone to ignore the summary line.

import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..");
const WINDOWS = process.platform === "win32";

const args = process.argv.slice(2);
if (args.includes("--help") || args.includes("-h")) {
  console.log(
    [
      "node scripts/gates.mjs [--plan]",
      "",
      "Runs typecheck, lint and build (as CI's `check` job does), every one of them",
      "even after a failure, then prints `gates: typecheck=N lint=N build=N` and",
      "exits non-zero if any gate did.",
      "",
      "  --plan   also run scripts/check-test-plan.mjs, reported as test-plan=N",
    ].join("\n"),
  );
  process.exit(0);
}
const unknown = args.filter((a) => a !== "--plan");
if (unknown.length) {
  console.error(`gates: unknown argument ${unknown.join(" ")} — see --help`);
  process.exit(2);
}

// The binaries the three scripts call. Checked by file rather than by running
// them, because a half-linked .bin is exactly the state where running them
// produces output that looks like an ordinary failure.
const BINS = ["next", "tsc", "eslint"];
const missing = BINS.filter((b) => !existsSync(path.join(repo, "node_modules", ".bin", WINDOWS ? `${b}.cmd` : b)));
if (missing.length) {
  console.error(
    [
      `gates: node_modules/.bin has no ${missing.join(", ")} — nothing was run.`,
      "",
      "npm ci has not finished here, or never ran. Wait for `worktree.mjs new` to",
      "exit, or run `npm ci`, and try again. Running the gates now would fail every",
      "one of them for a reason that has nothing to do with the code.",
    ].join("\n"),
  );
  process.exit(2);
}

const gates = [
  { name: "typecheck", cmd: "npm run typecheck" },
  { name: "lint", cmd: "npm run lint" },
  { name: "build", cmd: "npm run build" },
];
if (args.includes("--plan")) gates.push({ name: "test-plan", cmd: "node scripts/check-test-plan.mjs" });

const results = [];
for (const gate of gates) {
  console.log(`\n=== gates: ${gate.name} — ${gate.cmd}\n`);
  const started = Date.now();
  // One command string with a shell, because npm is a .cmd shim on Windows and
  // Node no longer spawns those without one. The commands are the constants
  // above, so there is nothing to quote.
  const r = spawnSync(gate.cmd, { cwd: repo, stdio: "inherit", shell: true });
  const seconds = Math.round((Date.now() - started) / 1000);
  // A gate that could not be started, or was killed by a signal, has no exit
  // code; it is reported as what happened and counts as a failure.
  const code = r.error ? "error" : r.status ?? r.signal ?? "killed";
  results.push({ ...gate, code, seconds });
  console.log(`\n=== gates: ${gate.name} exited ${code} after ${seconds}s`);
}

const failed = results.filter((r) => r.code !== 0);
console.log("");
if (failed.length) {
  console.log(`gates: FAILED — ${failed.map((r) => r.name).join(", ")}`);
}
console.log(`gates: ${results.map((r) => `${r.name}=${r.code}`).join(" ")}`);
process.exit(failed.length ? 1 : 0);
